version: "2"
services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    environment:
      - APP_PORT=${APP_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_USERNAME=${SPOTIFY_USERNAME}
      - SPOTIFY_REDIRECT_URL=${SPOTIFY_REDIRECT_URL}
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["pipenv", "run", "python", "main.py"]
